[build-system]
requires = [
    "pyttsx3",
    "PyAudio",
    "pydub",
    "websockets",
    "pywin32",
    "pandas",
    "numpy",
    "clean-text",
    "pdfplumber",
    "pymorphy2",
    "configparser",
]
build-backend = "setuptools.build_meta"